"""Added device FKs

Revision ID: feef6f859249
Revises: ebdb19a8cfc6
Create Date: 2024-11-23 12:20:07.498716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feef6f859249'
down_revision: Union[str, None] = 'ebdb19a8cfc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'device', 'user', ['user_id'], ['id'])
    op.add_column('devicetype', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('devicetype', sa.Column('device_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'devicetype', 'device', ['device_id'], ['id'])
    op.create_foreign_key(None, 'devicetype', 'user', ['user_id'], ['id'])
    op.add_column('switch', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('switch', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'switch', 'devicetype', ['type_id'], ['id'])
    op.create_foreign_key(None, 'switch', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'switch', type_='foreignkey')
    op.drop_constraint(None, 'switch', type_='foreignkey')
    op.drop_column('switch', 'type_id')
    op.drop_column('switch', 'user_id')
    op.drop_constraint(None, 'devicetype', type_='foreignkey')
    op.drop_constraint(None, 'devicetype', type_='foreignkey')
    op.drop_column('devicetype', 'device_id')
    op.drop_column('devicetype', 'user_id')
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column('device', 'user_id')
    # ### end Alembic commands ###
